{% set name = "xtcocotools" %}
{% set version = "1.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6434382784d206204d2a1b491dba359ff3464a2b9eb5890fbc0d868cad4e810f

build:
  number: 5
  script:
    - {{ PYTHON }} -c "content = open('setup.py').read().replace('version=get_version(),', 'version=\'{{ version }}\','); open('setup.py', 'w').write(content)"
    - {{ PYTHON }} -c "from pathlib import Path; p = Path('requirements.txt'); p.write_text('\n'.join(line for line in p.read_text().splitlines() if not line.lower().startswith(('cython', 'setuptools'))) + '\n')"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools >=18.0
  run:
    - matplotlib-base
    - python

test:
  imports:
    - xtcocotools
    - xtcocotools.mask
  commands:
    - python -c "import numpy as np; from xtcocotools import mask; arr = np.asfortranarray([[0, 1], [1, 1]], dtype=np.uint8); rle = mask.encode(arr); assert int(mask.area(rle)) == 3; assert np.array_equal(mask.decode(rle), arr)"
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/jin-s13/xtcocoapi
  summary: Extended COCO-API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
