{% set name = "xtcocotools" %}
{% set version = "1.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6434382784d206204d2a1b491dba359ff3464a2b9eb5890fbc0d868cad4e810f

build:
  number: 2
  script:
    - {{ PYTHON }} -c "import os,io; d='xtcocotools'; os.makedirs(d, exist_ok=True); p=os.path.join(d,'__init__.py'); io.open(p,'a',encoding='utf-8').write('\n__version__ = \'{{ version }}\'\n')"
    - {{ PYTHON }} -c "content = open('setup.py').read().replace('version=get_version(),', 'version=\'{{ version }}\','); open('setup.py', 'w').write(content)"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - matplotlib
    - numpy
    - pip
    - python
    - setuptools >=18.0
  run:
    - cython
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - xtcocotools
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/jin-s13/xtcocoapi
  summary: Extended COCO-API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
